name: DesaA-Branch Unmanaged
# Exportar solución desde Desa A - Administrada y No Administrada
# unpack y preparar, confirmar y generar una branch git temporal con los cambios
on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'Nombre de la solución. Sería la full o la mini, TBD'
        required: true
        default: SLASOL2
       #Do Not change these values
      solution_exported_folder:
        description: 'nombre de la carpeta para almacenar la solución exportada *no cambiar*.'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Preparación de la carpeta de la solución desempaquetada antes del registro *no modificar*.'
        required: true
        default: out/solutions/
      solution_target_folder: 
       description: 'nombre de la carpeta que debe crearse y registrarse *no modificar*.'
       required: true
       default: solutions/
       
env:
  ENVIRONMENT_URL: 'https://dev330rs.crm.dynamics.com/'
  CLIENT_ID: 'a6179c2f-6dab-4113-860b-62423845a814'
  TENANT_ID: 'ab7e124e-3be3-41ef-a0f4-9b9b8c703eef'
permissions:
  contents: write

jobs:
  exportar-desaA:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
     
    #- name: Install Power Platform Tools
    #  uses: microsoft/powerplatform-actions/actions-install@v0
      
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}

    - name: export-solution action -unmanaged
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true
        use-unmanaged-file-for-missing-managed: true

    - name: branch-solution, preparar para PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        clobber-branch: true
        branch-name: DesaA
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
