name: Ejecucion concatenado
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
 workflow_dispatch:
 
permissions:
  contents: write
jobs:
  Exportar-sol-branch-desaa:
    uses: ./.github/workflows/WF000 -export-desaa-branch.yml
    with:
      #You can specify the solution name here
      solution_name: DEMOSOL01
      #Update your values here
      solution_exported_folder: /out
      solution_folder: /solution
      solution_target_folder: solution
      BUILD_ENVIRONMENT_URL: smartdemodesaa.crm.dynamics.com
      PRODUCTION_ENVIRONMENT_URL: smartdemoprod.crm.dynamics.com
      CLIENT_ID: 'a4dedf07-6b5f-4f68-bf14-3dc809f12cc7'
      TENANT_ID: 'c38716e6-6e98-4055-a98a-7189a099f652'
      
    secrets:
      envSecret: ${{ secrets.GITHUBAPPA }}
