name: Ejecucion concatenado
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
 workflow_dispatch:
 
permissions:
  contents: write
  
jobs:
  Exportar-sol-branch-desaa:
    uses: ./.github/workflows/WF000 -export-desaa-branch.yml
    with:
      #You can specify the solution name here
      solution_name: DEMOSOL01
      #Update your values here
      solution_exported_folder: /out
      solution_folder: /solution
      solution_target_folder: solution
      DESAA_ENVIRONMENT_URL: https://smartdemodesaa.crm.dynamics.com
      CLIENT_ID_A: 'a4dedf07-6b5f-4f68-bf14-3dc809f12cc7'
      TENANT_ID_A: 'c38716e6-6e98-4055-a98a-7189a099f652' 
    secrets:
       envSecretA: ${{ secrets.SecretAppA }}
  
  Exportar-sol-branch-INTEA:
    uses: ./.github/workflows/WF001a-import-desab-unmanaged.yml
    with:
      #You can specify the solution name here
      solution_name: DEMOSOL01
      #Update your values here
      solution_exported_folder: /out
      solution_folder: /solution
      solution_target_folder: solution
      DESAB_ENVIRONMENT_URL: https://smartdemodesab.crm.dynamics.com
      CLIENT_ID_B: 'a939822b-df70-4c40-a6cb-66446c1c798e'
      TENANT_ID_B: 'f0474298-6f07-4eb9-b686-421dc9d2095'  
    secrets:
       envSecretB: ${{ secrets.SecretAppB }}
