name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
 workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: DEMOSOL01
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: /out
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: /solution
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solution
env:
#edit your values here
  ENVIRONMENT_URL: 'https://smartdemodesaa.crm.dynamics.com/'
  CLIENT_ID: 'a4dedf07-6b5f-4f68-bf14-3dc809f12cc7'
  TENANT_ID: 'c38716e6-6e98-4055-a98a-7189a099f652'
permissions:
  contents: write
  
jobs:
  Exportar-sol-branch-desaa:
    uses: ./.github/workflows/WF000 -export-desaa-branch.yml
    with:
      #You can specify the solution name here
      solution_name: DEMOSOL01
      #Update your values here
      BUILD_ENVIRONMENT_URL: smartdemodesaa.crm.dynamics.com
      PRODUCTION_ENVIRONMENT_URL: <your prod server url>
      CLIENT_ID: a4dedf07-6b5f-4f68-bf14-3dc809f12cc7
      TENANT_ID: c38716e6-6e98-4055-a98a-7189a099f652 
      
    secrets:
      envSecret: ${{ secrets.GITHUBAPPA }}
