name: WF001a-branch importar unmanaged en desa B
# Empaquetar managed desde branch DESA A
# importar en AMBIENTE destino DESA B como unmanaged.
on:
  workflow_call:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        type: string
        required: true
        default: DEMOSOL01
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        type: string
        required: true
        default: /out
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        type: string
        required: true
        default: /solution
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       type: string
       required: true
       default: solution   
      BUILD_ENVIRONMENT_URL:
        description: 'Build environment url.'
        type: string
        required: true   
      PRODUCTION_ENVIRONMENT_URL: 
        description: 'Production environment url'
        type: string
        required: true
      CLIENT_ID: 
        description: 'The client id'
        type: string
        required: true
      TENANT_ID: 
        description: 'The tenant id'
        type: string
        required: true
 
    secrets:
      envSecret:
        description: 'The secret value for authentication using SPN'
        required: true

permissions:
  contents: write

jobs:
  importar-unmanaged:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    - uses: microsoft/powerplatform-actions/actions-install@v1

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{inputs.INTE_ENVIRONMENT_URL}}
        app-id: ${{inputs.CLIENT_ID}}
        client-secret: ${{ secrets.envSecret }}
        tenant-id: ${{inputs.TENANT_ID}}

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: ${{ inputs.solution_folder}}/${{ inputs.solution_name }}
        solution-file: ${{ inputs.solution_exported_folder}}/${{ inputs.solution_name }}.zip
        solution-type: Unmanaged
        
    - name: Importar-solucion-unmanaged
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{inputs.INTE_ENVIRONMENT_URL}}
        app-id: ${{inputs.CLIENT_ID}}
        client-secret: ${{ secrets.envSecret }}
        tenant-id: ${{inputs.TENANT_ID}}
        solution-file: ${{ inputs.solution_exported_folder}}/${{ inputs.solution_name }}.zip
        publish-changes: false
