name: WF001b-importar desde branch Desa A a INTE A
# Empaquetar managed desde branch desa A
# importar en INTE A como Mnaaged.
on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'Nombre de la solución. Sería la full o la mini, TBD'
        required: true
        default: DEMOSOL01
       #Do Not change these values
      solution_exported_folder:
        description: 'nombre de la carpeta para almacenar la solución exportada *no cambiar*.'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Preparación de la carpeta de la solución desempaquetada antes del registro *no modificar*.'
        required: true
        default: solution/
env:
#edit your values here
  INTE_ENVIRONMENT_URL: 'https://smartdemointea.crm.dynamics.com/'
  CLIENT_ID: 'a4dedf07-6b5f-4f68-bf14-3dc809f12cc7'
  TENANT_ID: 'c38716e6-6e98-4055-a98a-7189a099f652'
permissions:
  contents: write

jobs:
  importar-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    - uses: microsoft/powerplatform-actions/actions-install@v1

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{env.INTE_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.GITHUBAPPA }}
        tenant-id: ${{env.TENANT_ID}}

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip
        solution-type: Managed
        
    - name: Importar-solucion-administrada
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{env.INTE_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.GITHUBAPPA }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip
        publish-changes: false
