name: WF001-main importar en INTE A
# Empaquetar managed desde DEV
# importar en AMBIENTE destino
on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'Nombre de la solución. Sería la full o la mini, TBD'
        required: true
        default: SLASOL3
       #Do Not change these values
      solution_exported_folder:
        description: 'nombre de la carpeta para almacenar la solución exportada *no cambiar*.'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Preparación de la carpeta de la solución desempaquetada antes del registro *no modificar*.'
        required: true
        default: solution/
env:
#edit your values here
  INTE_ENVIRONMENT_URL: 'https://inteabg.crm.dynamics.com/'
  CLIENT_ID: 'a6179c2f-6dab-4113-860b-62423845a814'
  TENANT_ID: 'ab7e124e-3be3-41ef-a0f4-9b9b8c703eef'
permissions:
  contents: write

jobs:
  importar-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    - uses: microsoft/powerplatform-actions/actions-install@v1

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{env.INTE_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.APP_A }}
        tenant-id: ${{env.TENANT_ID}}

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip
        solution-type: Managed
        
    - name: Importar-solucion-administrada
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{env.INTE_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.APP_A }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip
        publish-changes: false
