name: WF002-MAIN importar en HOMO B
# Empaquetar managed desde TEMPORAL-BRANCH
# importar en AMBIENTE destino
on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'Nombre de la solución. Sería la full o la mini, TBD'
        required: true
        default: SLASOL3
       #Do Not change these values
      solution_exported_folder:
        description: 'nombre de la carpeta para almacenar la solución exportada *no cambiar*.'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Preparación de la carpeta de la solución desempaquetada antes del registro *no modificar*.'
        required: true
        default: solution/
env:
#edit your values here
  DEV_ENVIRONMENT_URL: 'https://desaabg.crm.dynamics.com/'
  INTE_ENVIRONMENT_URL: 'https://inteabg.crm.dynamics.com/'
  HOM_ENVIRONMENT_URL: 'https://homobbg.crm.dynamics.com/'
  CLIENT_ID: 'abde9fd6-c25b-4c3a-ad13-d53e0f8438d7'
  TENANT_ID: '97a862df-3e59-4f64-ba58-146ecb5993e7'
permissions:
  contents: write

jobs:
  importar-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    - uses: microsoft/powerplatform-actions/actions-install@v1

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{env.HOM_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.APP_B }}
        tenant-id: ${{env.TENANT_ID}}

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip
        solution-type: Managed
        
    - name: Importar-solucion-administrada
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{env.HOM_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.APP_B }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip
        publish-changes: false
