name: WF001b-importar desde branch Desa A a INTE A
# Empaquetar managed desde branch desa A
# importar en INTE A como Mnaaged.
on:
  workflow_call:
    inputs: 
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        type: string
        required: true
        default: DEMOSOL01
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        type: string
        required: true
        default: /out/exported
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        type: string
        required: true
        default: /solution
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       type: string
       required: true
       default: solution   
      INTEA_ENVIRONMENT_URL:
        description: 'INTEA environment url.'
        type: string
        required: true   
      CLIENT_ID_A: 
        description: 'The client id'
        type: string
        required: true
      TENANT_ID_A: 
        description: 'The tenant id'
        type: string
        required: true
 
    secrets:
      envSecretA:
        description: 'The secret value for authentication using SPN'
        required: true

permissions:
  contents: write

jobs:
  importar-managed:
    runs-on: windows-latest
    environment: INTE
    env:
      RUNNER_DEBUG: 1
      
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    - uses: microsoft/powerplatform-actions/actions-install@v1

    #- name: who-am-i action
    #  uses: microsoft/powerplatform-actions/who-am-i@v1
    #  with:
    #    environment-url: ${{imputs.INTEA_ENVIRONMENT_URL}}
    #    app-id: ${{inputs.CLIENT_ID_A}}
    #    client-secret: ${{ secrets.envSecretA }}
    #    tenant-id: ${{inputs.TENANT_ID_A}}

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: ${{ inputs.solution_target_folder}}/${{ inputs.solution_name }}
        solution-file: ${{ inputs.solution_exported_folder}}/${{ inputs.solution_name }}_managed.zip
        solution-type: Managed
        
    - name: Importar-solucion-administrada
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{inputs.INTEA_ENVIRONMENT_URL}}
        app-id: ${{inputs.CLIENT_ID_A}}
        client-secret: ${{ secrets.envSecretA }}
        tenant-id: ${{inputs.TENANT_ID_A}}
        solution-file: ${{ inputs.solution_exported_folder}}/${{ inputs.solution_name }}_managed.zip
        publish-changes: false
