name: export-solution-desde-desaa > branch
# Export solution from DESAA a branch managed-unmanaged. 
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_call:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        type: string
        required: true
        default: DEMOSOL01
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        type: string
        required: true
        default: /out
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        type: string
        required: true
        default: /solution
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       type: string
       required: true
       default: solution   
      DESAA_ENVIRONMENT_URL:
        description: 'DESAA environment url.'
        type: string
        required: true   
      CLIENT_ID_A: 
        description: 'The client id'
        type: string
        required: true
      TENANT_ID_A: 
        description: 'The tenant id'
        type: string
        required: true
 
    secrets:
      envSecretA:
        description: 'The secret value for authentication using SPN'
        required: true

permissions:
  contents: write

jobs:
  managed-unmanaged:
   name: managed-unmanaged
   runs-on: windows-latest
   env:
    RUNNER_DEBUG: 1
   steps:
    - uses: actions/checkout@v4
      with:
       lfs: true
       
    - uses: microsoft/powerplatform-actions/actions-install@v1
                
    - name: export-solution action -unmanaged
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{inputs.DESAA_ENVIRONMENT_URL}}
        app-id: ${{inputs.CLIENT_ID_A}}
        client-secret: ${{ secrets.envSecretA }}
        tenant-id: ${{inputs.TENANT_ID_A}}
        solution-name: ${{ inputs.solution_name }}
        solution-output-file: ${{ inputs.solution_exported_folder}}/${{ inputs.solution_name }}.zip    

    - name: export-solution action -managed
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{inputs.DESAA_ENVIRONMENT_URL}}
        app-id: ${{inputs.CLIENT_ID_A}}
        client-secret: ${{ secrets.envSecretA }}
        tenant-id: ${{inputs.TENANT_ID_A}}
        solution-name: ${{ inputs.solution_name }}
        managed: true
        solution-output-file: ${{ inputs.solution_exported_folder}}/${{ inputs.solution_name }}_managed.zip
  
  unpack_solution:
   name: unpack_solution
   needs: managed-unmanaged
   runs-on: windows-latest
   env:
    RUNNER_DEBUG: 1
   steps:
    - uses: actions/checkout@v4
      with:
       lfs: true
    - uses: microsoft/powerplatform-actions/actions-install@v1
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: ${{ inputs.solution_exported_folder}}/${{ inputs.solution_name }}.zip
        solution-folder: ${{ inputs.solution_folder}}/${{ inputs.solution_name }}
        solution-type: 'Both'
        overwrite-files: true
  Create_branch:
   name: create_branch
   needs: unpack_solution
   runs-on: windows-latest
   env:
    RUNNER_DEBUG: 1
   steps:
    - uses: actions/checkout@v4
      with:
       lfs: true
    - uses: microsoft/powerplatform-actions/actions-install@v1
    - name: branch-solution
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        branch-name: TEMP_BRANCH_desaA
        solution-folder: ${{ inputs.solution_folder}}/${{ inputs.solution_name }}
        solution-target-folder: ${{ inputs.solution_target_folder}}/${{ inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
