name: WF001b-importar desde branch Desa A a INTE A
# Empaquetar managed desde branch desa A
# importar en INTE A como Mnaaged.
on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'Nombre de la solución. Sería la full o la mini, TBD'
        required: true
        default: DEMOSOL01
       #Do Not change these values
      solution_exported_folder:
        description: 'nombre de la carpeta para almacenar la solución exportada *no cambiar*.'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Preparación de la carpeta de la solución desempaquetada antes del registro *no modificar*.'
        required: true
        default: solution/
      
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        type: string
        required: true
        default: DEMOSOL01
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        type: string
        required: true
        default: /out
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        type: string
        required: true
        default: /solution
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       type: string
       required: true
       default: solution   
      DESAB_ENVIRONMENT_URL:
        description: 'DesaB environment url.'
        type: string
        required: true   
      CLIENT_ID_B: 
        description: 'The client id'
        type: string
        required: true
      TENANT_ID_B: 
        description: 'The tenant id'
        type: string
        required: true
 
    secrets:
      envSecretB:
        description: 'The secret value for authentication using SPN'
        required: true

permissions:
  contents: write

jobs:
  importar-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    - uses: microsoft/powerplatform-actions/actions-install@v1

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{env.INTE_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.GITHUBAPPA }}
        tenant-id: ${{env.TENANT_ID}}

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip
        solution-type: Managed
        
    - name: Importar-solucion-administrada
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{env.INTE_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.GITHUBAPPA }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip
        publish-changes: false
