
name: WF003-RELEASE importar en PRODUCCIÓN
# Empaquetar managed desde branch RELEASE
# importar en PRODUCCION
on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'Nombre de la solución. Sería la full o la mini, TBD'
        required: true
        default: SLASOL3
       #Do Not change these values
      solution_exported_folder:
        description: 'nombre de la carpeta para almacenar la solución exportada *no cambiar*.'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Preparación de la carpeta de la solución desempaquetada antes del registro *no modificar*.'
        required: true
        default: solution/
        
env:
#edit your values here
  HOM_ENVIRONMENT_URL: 'https://homocbg.crm.dynamics.com/'
  CLIENT_ID: '4030c838-68a1-4f5f-a0f1-11f789946181'
  TENANT_ID: 'f1babdc2-016c-44c7-963f-a0deb78b2c32'
permissions:
  contents: write

jobs:
  importar-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
   
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: microsoft/powerplatform-actions/actions-install@v1
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{env.HOM_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.APP_C }}
        tenant-id: ${{env.TENANT_ID}}

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip
        solution-type: Managed
        
    - name: Importar-solucion-administrada
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{env.HOM_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.APP_C }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip
        publish-changes: false
